### PR TITLE
62 populate uses from db

### PR DESCRIPTION
**Pull request by daynewright**
## Status

**READY**
## Documentation

[ X] I have fully documented features in this PR. Please put an `X` in the box to confirm.
## Migrations

NO
## Description
- Adds `NavbarView.cshtml` partial to shared views
- Adds `Users` class and method to `Helpers` namespace
- Adds method `GetAllUsers` to `Users` class
- Adds dropdown of all users from database through `GetAllUsers` method to `NavbarView.cshtml` partial
## Resolves Issue Number
#62
## Deploy Notes

Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.
## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.

``` sh
git pull --prune
git checkout 62-populate-uses-from-DB
dotnet run
```
1. 
## Impacted Areas in Application

List general components of the application that this PR will affect:
- `_Layout.cshtml`
- `SessionHelper.cs`
- `UserController.cs` and `ProductController.cs` both add `ViewBag.Users = Users.GetAllUsers(context);`  to view model

### CODE REVIEW

**Comment by garrett-vangilder** [comment]
LGTM

**Comment by garrett-vangilder** [comment]
screen shot 2016-10-25 at 9 52 32 am

this does look strange though

**Comment by daynewright** [comment]
@garrett-vangilder  Correct.  This pull request does not address any styling or UX issues.

**Comment by MattKraatz** [comment]
LGTM

**Comment by Anulfo** [comment]
LGTM

**Review by MattKraatz — APPROVED** [review]
Needs refactoring but works for now

**Pull request merged**
