### PR TITLE
108-add-to-cart :: updated Add to Cart link and Cart Index with ActiveUser

### LINKED ISSUE #108: Update Add to Cart Functionality
### Feature Description

Currently the "Add to Cart" link is displayed on every Product Detail page. Users should not see this link if they own the current product. Maybe display an edit and delete link instead?

Add to Cart link is broken.
### Recommended Actions

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.
1. Update the razor template with a simple If statement checking the product ID against the active user ID
2. See the ProductTypes/List view to see this in action

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status

**READY**
## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.
## Description

Update the Add to Cart Link, and the Cart Index view to reference the Active User instead of a dummy user.
## Resolves Issue Number

Resolves #108 
## Deploy Notes

``` sh
git pull --prune
git checkout 108-add-to-cart
dotnet run
```
## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
1. Log in
2. Navigate to a Product Detail page
3. You should only be able to add a product to your cart if you are NOT the seller of that product
4. If you are the seller of that product, you should see an Edit and Delete icon on the product detail view instead of "Add to Cart"
5. Add products to your cart
6. Confirm that those items are in your cart
7. Log in as a different user, make sure they have a different cart
## Impacted Files in Application

List general components of the application that this PR will affect:
- Views/Products/Detail
- Controllers/Cart

### CODE REVIEW

**Review by Anulfo — COMMENTED** [review]
It worked and LGTM

**Comment by garrett-vangilder** [comment]
LGTM

~~I didn't have to use the `Instance` portion of Active User in my version. Not too sure if that matters.~~

**Comment by Anulfo** [comment]
LGTM

**Comment by daynewright** [comment]
So this does not impact the `/ProductTypes/List` view?

**Comment by daynewright** [comment]
LGTM

**Pull request merged**
