### PR TITLE
43-SessionHelper - Added class to track logged in user

### PR DESCRIPTION
**Pull request by matthamil**
## Status

**READY**
## Documentation

[X] I have fully documented features in this PR. Please put an `X` in the box to confirm.
## Migrations

NO
## Description

Added a static class called `SessionHelper` inside the `Bangazon.Helpers` namespace. `SessionHelper` does **not** have to be instantiated to be used since it is `static`.

Usage:

``` CSharp
Customer myCustomer = new Customer();
SessionHelper.ActiveUser = myCustomer;
```
## Resolves Issue Number
#43
## Deploy Notes

New migrations or database reset should not be necessary.
## Steps to Test or Reproduce

``` sh
git pull --prune
git checkout 43-SessionHelper
dotnet restore
dotnet run
```
## Impacted Areas in Application

Added `Helpers` directory in the root.

### CODE REVIEW

**Comment by matthamil** [comment]
@TeamCharles/team Ready for review

**Comment by daynewright** [comment]
👍

**Review by garrett-vangilder — APPROVED** [review]

**Comment by garrett-vangilder** [comment]
LGTM

**Review by MattKraatz — APPROVED** [review]
LGTM

**Comment by MattKraatz** [comment]
@matthamil wanna merge?

**Comment by Anulfo** [comment]
LGTM but I have questions for tomorrow!

**Pull request merged**
