### PR TITLE
Kraatz bug fixes

### LINKED ISSUE #155: Checkout button clickable with empty cart
### Bug Description

When logged in as any user with an empty cart, clicking on the shopping cart takes you to the cart, but the `checkout` button is enabled, allowing the user to progress to an empty order completion page.

### Recommended Actions

Disable/hide the checkout button for carts with no items

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status
**READY**

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.

## Description
Fix a few bugs surfaced during QA.

## Resolves Issue Number
Resolves #155 and #156 

## Deploy Notes

```sh
git pull --prune
git checkout "kraatz-bug-fixes"
dotnet run
```

### CODE REVIEW

**Comment by daynewright** [comment]
LGTM 🌮

**Comment by garrett-vangilder** [comment]
LGTM 🇹🇯

**Comment by matthamil** [comment]
yes

**Review by matthamil — APPROVED** [review]
yep that's code

**Pull request merged**
