### PR TITLE
92-viewAllProductsBtn - All Products Button

### PR DESCRIPTION
**Pull request by matthamil**
## Status

**READY**
## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.
## Description

A button on the Home Page that redirects the user to a list of all products
## Resolves Issue Number

https://github.com/TeamCharles/initial-site/issues/92
## Deploy Notes

``` sh
git pull --prune
git checkout 92-viewAllProductsBtn
dotnet run
```
## Steps to Test or Reproduce
1.  Go to `localhost:5000`
2. Click `View All Products` button
3. You should be redirected to `localhost:5000/Products`
## Impacted Files in Application
- Views/Products/Index.cshtml

### CODE REVIEW

**Comment by matthamil** [comment]
@TeamCharles/team Ready for review

**Comment by daynewright** [comment]
LGTM

**Comment by garrett-vangilder** [comment]
LGTM

**Review by MattKraatz — APPROVED** [review]
LGTM. Opening a separate issue for refactoring the Products/Index View

**Comment by Anulfo** [comment]
LGTM

**Pull request merged**
