### PR TITLE
63-user-form-validation :: added form validation to user creation

### LINKED ISSUE #63: Form Validation on User Creation
### Feature Description

Deliver in-line validation messages on the User/New view when a user submits data that doesn't fit the model
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status

**READY**
## Documentation

[X] I have fully documented features in this PR. Please put an `X` in the box to confirm.
## Migrations

NO
## Description

Display validation messages if a user submits data that doesn't fit the user model.
## Related PRs

N/A
## Resolves Issue Number

resolves #63 
## Deploy Notes

N/A
## Steps to Test or Reproduce
- Navigate to "Create a User"
- Fuck up the form
- Try to submit

``` sh
git pull --prune
git checkout 63-user-form-validation
dotnet run
```
## Impacted Areas in Application

List general components of the application that this PR will affect:
- User Creation form

### CODE REVIEW

**Comment by garrett-vangilder** [comment]
LGTM

**Comment by daynewright** [comment]
LGTM

**Comment by matthamil** [comment]
Could add decorators above each `User` model property that needs a space in it like so:

``` Csharp
[Required]
[Display (Name = "First Name")]
public string FirstName { get; set; }
```

**Comment by MattKraatz** [comment]
@matthamil please review dawg

**Pull request merged**
