### PR TITLE
47-lineItemModel - Updated the Line Item Model

### PR DESCRIPTION
**Pull request by matthamil**
## Status

**READY**
## Documentation

[X] I have fully documented features in this PR. Please put an `X` in the box to confirm.
## Migrations

NO
## Description

A few sentences describing the overall goals of the pull request's commits.
## Resolves Issue Number
#47
## Steps to Test or Reproduce

``` sh
git pull --prune
git checkout 47-lineItemModel
rm bangazon.db
rm -rf Migrations/
dotnet ef migrations add Initial
dotnet ef database update
dotnet restore
dotnet run
```
## Impacted Areas in Application

List general components of the application that this PR will affect:
- Models/

### CODE REVIEW

**Comment by matthamil** [comment]
@TeamCharles/team

**Comment by MattKraatz** [comment]
LGTM

**Comment by matthamil** [comment]
LGTM

**Comment by garrett-vangilder** [comment]
LGTM

**Comment by daynewright** [comment]
LGTM

**Comment by MattKraatz** [comment]
@matthamil need a generator on the context file

**Comment by matthamil** [comment]
@TeamCharles/team @MattKraatz Fixed `BangazonContext`

**Comment by garrett-vangilder** [comment]
LGTM

**Comment by MattKraatz** [comment]
LGTM

**Comment by Anulfo** [comment]
LGTM

**Comment by daynewright** [comment]
LGTM

**Review by Anulfo — APPROVED** [review]
LGTM

**Pull request merged**
