### PR TITLE
35-product-model Updated Product Model per ERD

### LINKED ISSUE #35: Check/Update Product Model
### Feature Description

Product Model must contain:
- ProductId [PK]
- ProductTypeId [FK]
- UserId [FK]
- IsActive [boolean]
- Name [string]
- Description [string]
- Price [float]
- DateCreated [date(autogenerated)]
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status

**READY**
## Documentation

[X] I have fully documented features in this PR. Please put an `X` in the box to confirm.
## Migrations

YES
## Description

Added DateCreation generator to BangazonContext. Changed Price type from double to float. Added ProductType FK.
## Related PRs

None
## Resolves Issue Number

resolves #35 
## Steps to Test or Reproduce

Probably have to nuke your Migrations folder and Bangazon.db file.

``` sh
git pull --prune
git checkout 35-product-model
dotnet ef migrations add initial
dotnet ef database update
dotnet run
```
1. 
## Impacted Areas in Application

List general components of the application that this PR will affect:
- Product Model
- Bangazon Context

### CODE REVIEW

**Comment by MattKraatz** [comment]
@TeamCharles/team ready for review homies

**Comment by garrett-vangilder** [comment]
Remember to delete your database, then everything works well! 

LGTM Good job.

**Comment by matthamil** [comment]
``` sh
git pull --prune
git checkout 35-product-model
rm -rf Migrations
rm bangazon.db
dotnet ef migrations add initial
dotnet ef database update
dotnet run
```

^ Commands I used to get this PR working

**Comment by daynewright** [comment]
👍

**Review by matthamil — APPROVED** [review]
LGTM

**Pull request merged**
