### PR TITLE
34-new-user: add a new user to the db

### LINKED ISSUE #34: User Database Update
### Feature Description

The database should be updated once the user has completed the new user form.
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.

Once the user has completed the form and clicked the submit button, the following should happen: 
1. The database is updated to include the new user information.
2. The product types or products being sold view is shown.

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status

**READY**
## Documentation

[X] I have fully documented features in this PR. Please put an `X` in the box to confirm.
## Migrations

NO
## Description

Allow users to create a new user account
## Resolves Issue Number

resolves #34 
I'll create a new issue about updating the navigation bar with the new users' information.
## Steps to Test or Reproduce
- run the program
- navigate to http://localhost:5000/user/new
- populate the form
- click "Create User"
- open your db file in DB Browser for SQLite to confirm the new user was added

``` sh
git pull --prune
git checkout 34-new-user
dotnet run
```
1. 
## Impacted Areas in Application

List general components of the application that this PR will affect:
- user creation

### CODE REVIEW

**Comment by MattKraatz** [comment]
I'm not sure how to handle form validation yet, opening a separate Issue for that. Right now it's just returning a JSON response if any form element is invalid.

**Comment by garrett-vangilder** [comment]
This looks fairly complex. I'm requesting that we all look at this together tomorrow with a walk through.

**Comment by matthamil** [comment]
LGTM

**Comment by Anulfo** [comment]
LGTM

**Comment by daynewright** [comment]
LGTM

**Comment by garrett-vangilder** [comment]
LGTM

**Review by matthamil — APPROVED** [review]
check out that code ( ͡° ͜ʖ ͡°)

**Comment by daynewright** [comment]
LGTM

**Review by garrett-vangilder — APPROVED** [review]

**Pull request merged**
