### PR TITLE
83 changed navbar to allow for user to navigate towards product creation…

### PR DESCRIPTION
**Pull request by garrett-vangilder**
## Status

**READY
## Documentation

[X] I have fully documented features in this PR. Please put an `X` in the box to confirm.
## Migrations

NO
## Description

A few sentences describing the overall goals of the pull request's commits.

You are now allowed to navigate to product creation through the navbar.
## Related PRs

List related PRs against other branches:

| branch | PR |
| --- | --- |
| other_pr_production | [link]() |
| other_pr_master | [link]() |
## Resolves Issue Number

number [link]()
#83
## Deploy Notes

Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.
## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.

``` sh
git pull --prune
git checkout 83-item-creation
dotnet run
```
1. 
## Impacted Areas in Application

List general components of the application that this PR will affect:
- New View, Product Controller, Navbar

… form

### CODE REVIEW

**Review by matthamil — CHANGES_REQUESTED** [review]
Documentation is out of date

**Review by matthamil — APPROVED** [review]

**Comment by matthamil** [comment]
LGTM 🍰

**Comment by MattKraatz** [comment]
LGTM

**Comment by Anulfo** [comment]
LGTM

**Pull request merged**
