### PR TITLE
38-producttype-model  - Added Product Type Model

### PR DESCRIPTION
**Pull request by daynewright**
## Status

**READY**
## Documentation

[ ] I have fully documented features in this PR. Please put an `X` in the box to confirm.
## Migrations

YES
## Description

Added Product Type model to reflect ERD.
## Related PRs

List related PRs against other branches:
NONE
## Resolves Issue Number

 #38 
## Deploy Notes

dotnet run
## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.

``` sh
git pull --prune
git checkout 38-producttype-model
rm bangazon.db
rm -rf Migrations/
dotnet ef migrations add Initial
dotnet ef database update
dotnet restore
bower install
open -a 'Google Chrome' 'http://localhost:5000' && dotnet run
done
```
## Impacted Areas in Application

List general components of the application that this PR will affect:
- Models/

### CODE REVIEW

**Comment by MattKraatz** [comment]
@daynewright don't we need to add ProductType to the Bangazon context file?

Also, DateCreated will need a auto-generator on that same context file.

**Comment by daynewright** [comment]
@TeamCharles/maintainers  Updated per @MattKraatz  comments.

**Comment by garrett-vangilder** [comment]
LGTM

**Comment by MattKraatz** [comment]
LGTM

**Comment by matthamil** [comment]
:shipit:

**Comment by Anulfo** [comment]
LGTM

**Comment by matthamil** [comment]
LGTM

**Comment by garrett-vangilder** [comment]
LGTM

**Review by matthamil — APPROVED** [review]
:+1:

**Comment by daynewright** [comment]
LGTM

**Pull request merged**
