### PR TITLE
140-UpdateEditProductSubTypes :: Updated Edit Product

### PR DESCRIPTION
**Pull request by daynewright**
## Status
**READY**

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.

## Description
Updated the edit functionality to include the sub product type options.

## Resolves Issue Number
#140 

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

```sh
git pull --prune
git checkout 140-UpdateEditProductSubTypes
dotnet run
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1.  dotnet run
2. login as a user
3. select a product to edit
4. change product types and sub product types
5. update product

## Impacted Files in Application
List general components of the application that this PR will affect:

* Controllers/ProductsController.cs
* ViewModels/ProductEdit.cs 
* Views/ProductSubTypes/Products.cshtml
* Views/Products/Edit.cshtml
* Views/Products/EditInfo.cshtml (DELETED)
* Views/Products/Index.cshtml
* wwwroot/js/site.js

### CODE REVIEW

**Review by MattKraatz — APPROVED** [review]
LGTM

**Comment by matthamil** [comment]
LGTM :hankey:

**Comment by garrett-vangilder** [comment]
LGTM

**Comment by Anulfo** [comment]
LGTM

**Pull request merged**
