### PR TITLE
79-view-model-refactor :: Refactor Views to accept View Models

### LINKED ISSUE #79: ViewModel Refactor
### Feature Description
- Update every view across the application to accept a view model instead of a model.
- ~~Move the User dropdown helper to a BaseViewModel class.~~
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.
> *User Dropdown in NavBar

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status

**READY**
## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.
## Description

Update all methods that return a `View()` to accept a viewmodel instead: `View(model)`. Every ViewModel inherits from the BaseViewModel, which stores a list of all Users and the CurrentUser.
## Resolves Issue Number

Resolves #79 
## Deploy Notes

``` sh
git pull --prune
git checkout 79-view-model-refactor
dotnet run
```
## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
- Make sure you can retrieve every view
  - ProductTypes List
  - Products List
  - Product Detail
  - Add a Product
  - Add a User
  - Cart
## Impacted Files in Application

List general components of the application that this PR will affect:
- All Views
- All Controller Methods that return a View
- Created ViewModel folder with several new Model classes

### CODE REVIEW

**Comment by daynewright** [comment]
@MattKraatz  Looks great!  I finally got it figured out too and then saw your commit . :) 

Did you intentionally remove the user dropdown from the navbar?

**Comment by MattKraatz** [comment]
@daynewright Yeah I deleted that component because it was giving me issues on this branch and it was working on the other User pull request I have open. Idk if that will give us any weird merge conflicts.

**Comment by garrett-vangilder** [comment]
LGTM

Unfortunately there are now merge conflicts. :(

**Comment by Anulfo** [comment]
LGTM

**Review by daynewright — APPROVED** [review]
🌮

**Pull request merged**
