### PR TITLE
kraatz-bugsquash

### LINKED ISSUE #99: UserCreate ViewModel requires CurrentUser
### Feature Description

In order to create a new account, you must have already "logged in" by selecting a user from the dropdown in the navbar.
### Recommended Actions

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.
- The UserCreate viewmodel should be valid even if no user is currently logged in.
- Remove its inheritance from BaseViewModel
- Add this code to the UserCreate viewmodel so that it's still available to the navbar partial

```
public IEnumerable<SelectListItem> Users { get; set; }
    protected BangazonContext context;

public BaseViewModel(BangazonContext ctx)
    {
        context = ctx;
        this.Users = context.User
            .OrderBy(l => l.LastName)
            .AsEnumerable()
            .Select(li => new SelectListItem { 
                Text = $"{li.FirstName} {li.LastName}",
                Value = li.UserId.ToString()
            });
    }
    public BaseViewModel() { }
```
- I think that should do it?

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status

**IN DEVELOPMENT**

I messed up and made this branch off of Dayne's JSON ProductSubType fix. After that PR is merged, I'll review merge conflicts and update this PR.
## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.
## Description
- A lot of route fixing
- Display "Please Log In" messages on Products/Detail and Cart views
- Fix Create User bug that required login before creating a user
## Resolves Issue Number

Resolve #99 
## Deploy Notes

``` sh
git pull --prune
git checkout kraatz-bugsquash
dotnet run
```
## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
1. Navigate down to Product/Detail and then go all the way back
2. Click View All Products button
3. Try to create a user without having logged in
4. Try to add a product to your cart or view your cart without having logged in
## Impacted Files in Application

List general components of the application that this PR will affect:
- Most Views

### CODE REVIEW

**Comment by garrett-vangilder** [comment]
LGTM

**Comment by garrett-vangilder** [comment]
Works very well too

**Comment by matthamil** [comment]
In the `View All Products` view, the products list is sorted alphabetically, but it distinguishes between product titles starting with a capital or lower case letters (sorted A-Z then a-z). See example:

image

Products (starting with a capital letter) are sorted, and then the list starts over alphabetically sorted for products starting with a lower case letter.

**Comment by daynewright** [comment]
LGTM

**Comment by MattKraatz** [comment]
Good catch @matthamil, fixed with a .ToLower in my OrderBy queries

**Pull request merged**
