### PR TITLE
Updated ProductsController Documentation

### PR DESCRIPTION
**Pull request by daynewright**
## Status
**READY/IN DEVELOPMENT**

## Documentation

[X] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.

## Description
A few sentences describing the overall goals of the pull request's commits.

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

```sh
git pull --prune
git checkout <feature_branch>
dotnet run
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1. 

## Impacted Files in Application
List general components of the application that this PR will affect:

*

### CODE REVIEW

**Comment by garrett-vangilder** [comment]
LGTM

**Review by MattKraatz — APPROVED** [review]
LGTM

**Comment by Anulfo** [comment]
LGTM

**Comment by matthamil** [comment]
:hankey:

**Pull request merged**
