### PR TITLE
Validate Order Model against ERD

### LINKED ISSUE #46: Check/Update Order Model
### Feature Description

Order Model must contain:
- OrderId [PK]
- UserId [FK]
- PaymentTypeId [FK]
- DateCreated [date(autogenerated)]
- DateCompleted [date(autogenerated)]
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status

**READY**
## Documentation

[X] I have fully documented features in this PR. Please put an `X` in the box to confirm.
- No documentation required
## Migrations

YES
## Description

Reviewed the order model against the ERD. Added a Required attribute to the CustomerID. CustomerID will need to be updated on a separate issue to UserID on update of the User model.
## Related PRs

None
## Resolves Issue Number

resolves #46 
## Steps to Test or Reproduce

``` sh
git pull --prune
git checkout <feature_branch>
dotnet run
```
1. 
## Impacted Areas in Application

List general components of the application that this PR will affect:
- model

### CODE REVIEW

**Comment by MattKraatz** [comment]
LGTM

**Comment by garrett-vangilder** [comment]
Received the following error "SQLite Error 1: 'no such column: p.CustomerId'

This pull request requires the following to run:
Delete Database 
Delete Migration File
Run `Bangazon Migration`
Run `Bangazon Run`
At that point this PR will pass.

**Comment by garrett-vangilder** [comment]
LGTM

**Comment by matthamil** [comment]
:shipit:

**Comment by Anulfo** [comment]
LGMT

**Review by matthamil — APPROVED** [review]
Gr8 work

**Comment by daynewright** [comment]
LGTM

**Pull request merged**
