### PR TITLE
67 complete order

### PR DESCRIPTION
**Pull request by garrett-vangilder**
## Status

**READY**
## Documentation

[X] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.
## Description

A few sentences describing the overall goals of the pull request's commits.

This will add a completed by date to the order. 
## Resolves Issue Number
#67
## Deploy Notes

Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

``` sh
git pull --prune
git checkout 67-complete-order
dotnet run
```
## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
1. Sign in as a user
2. Go to Cart
3. Click complete order
4. It will redirect you to the cart that is now empty, because the view only works with "active items"
5. Collect
## Impacted Files in Application

List general components of the application that this PR will affect:
- Cart Controller

### CODE REVIEW

**Comment by MattKraatz** [comment]
Order cannot be completed without a PaymentTypeId being associated with the order first. We probably need to get the Payment Type stuff working first.

**Review by Anulfo — COMMENTED** [review]
LGTM

**Comment by daynewright** [comment]
LGTM

**Review by daynewright — APPROVED** [review]
LGTM

**Pull request merged**
