### PR TITLE
9-create-product-type-controller - Initial boilerplate for product type controller

### PR DESCRIPTION
**Pull request by daynewright**
## Status

**READY**
## Documentation

[X ] I have fully documented features in this PR. Please put an `X` in the box to confirm.
## Migrations

NO
## Description

Created `ProductTypesController.cs` with two routes `Buy()` and `Sell()`.   They `Buy` method will be the main index route showing all product types that are currently for sale and do not belong to the logged in user.

Currently the controller simply outputs the data it receives from the database to the route view.  It will need to be fleshed out further.  This will be easier once seed data is added and able to be queried for testing.
## Related PRs

List related PRs against other branches:
## Resolves Issue Number
#9
## Deploy Notes

Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.
## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.

``` sh
git pull --prune
git checkout 9-create-product-type-controller 
dotnet run
```
## Impacted Areas in Application

List general components of the application that this PR will affect:
- startup.cs
- view templates

### CODE REVIEW

**Comment by daynewright** [comment]
@TeamCharles/team ready for review.

**Review by garrett-vangilder — APPROVED** [review]

**Comment by garrett-vangilder** [comment]
Runs on my machine, received an empty array, and I believe that was the intended result. LGTM!

**Comment by daynewright** [comment]
Correct.  You should receive an empty array.  This pull request simply makes a template and then after seed data is added the logic can be built out and tested.

**Comment by MattKraatz** [comment]
LGTM

**Comment by matthamil** [comment]
LGTM other than the fact that the `ProductTypesController` documentation is _technically_ wrong for the time being. Although I assume we'll be using a bunch of `async` stuff in the controller once the Views are fully fleshed out.

**Pull request merged**
