### PR TITLE
51-dbInitializer  added DbInitializer seed data

### LINKED ISSUE #51: Generate Seed Data with Dbinitializer
### Feature Description

Generate a Dbinitializer class that creates 3 users, 3 product types and 3 products for initial database data.
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.

None necessarily
### Notes

See Steve's repo.

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status

**READY**
## Documentation

[] I have fully documented features in this PR. Please put an `X` in the box to confirm.
## Description

Added a DbInitializer with seed data. Updated Startup.cs to run the DbInitializer on startup. Updated the User model to include a collection or PaymentTypes. 
## Resolves Issue Number

resolves #51 
## Deploy Notes

Probably need to nuke your Migration folder and bangazon.db file.
## Steps to Test or Reproduce

Fire up your program and then open the bangazon.db file in Sqlite Browser to make sure seed data has been populated.

``` sh
git pull --prune
git checkout 51-dbInitializer
dotnet run
```
1.

### CODE REVIEW

**Comment by MattKraatz** [comment]
@TeamCharles/team ready for review

**Comment by matthamil** [comment]
Users are lacking a `ZipCode` property:

From `Data/DbInitializer.cs`:

``` CSharp
var users = new User[]
{
  new User { 
    FirstName = "Carson",
    LastName = "Alexander",
    StreetAddress = "100 Infinity Way",
    City = "St. Paul",
    State = "Minnesota"
  },
  ...
};
```

From `Models/User.cs`:

``` CSharp
public class User
{
  [Key]
  public int UserId {get;set;}

  [Required]
  [DataType(DataType.Date)]
  [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
  public DateTime DateCreated {get;set;}

  [Required]
  public string FirstName { get; set; }

  [Required]
  public string LastName { get; set; }

  [Required]
  public string StreetAddress { get; set; }

  [Required]
  public string City {get; set;}

  [Required]
  public string State {get; set;}

  [Required]
  public int ZipCode {get; set;} // <--- ZipCode not set in DbInitializer.cs

  public ICollection<Product> Products;

  public ICollection<PaymentType> PaymentTypes;

}
```

**Comment by matthamil** [comment]
LGTM

**Comment by MattKraatz** [comment]
good catch @matthamil, fixed. I'm kinda surprised it still added those users to the db since ZipCode is required by the model.

**Comment by garrett-vangilder** [comment]
Just received a really strange error. Pretty sure it is due to SQlite.

**Comment by garrett-vangilder** [comment]
Got it fixed. LGTM. I love the throw pillow, and I hate SQLite.

**Comment by Anulfo** [comment]
It's working! LGTM

**Review by daynewright — APPROVED** [review]
Works great!

**Pull request merged**
