### PR TITLE
138-productIsActive - Using Product.IsActive

### PR DESCRIPTION
**Pull request by matthamil**
## Status
**READY**

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.

## Description
Changed the behavior of deleting a product. Products are now marked as `IsActive = false`. Products are never deleted from the database now. This is needed if we ever need to view past orders and a seller decides to stop selling a product.

## Resolves Issue Number

https://github.com/TeamCharles/initial-site/issues/138

## Deploy Notes

```sh
git pull --prune
git checkout 138-productIsActive
dotnet run
```

## Steps to Test or Reproduce

1. Log into an account

2. Add a product to your cart

3. Log out

4. Log into the account that is selling that original product

5. Find a product you are selling

6. Hit the "Delete" button next to the product to stop selling it.

7. Try to find it in the View All Products view

8. Try to find it in the Category view

9. Log back into first account

10. View your Cart (Unavailable item should be noted in your cart)

11. Confirm the order (Unavailable item should not be included in the Confirmation page)

## Impacted Files in Application
List general components of the application that this PR will affect:

* ProductsController

* CartController

* ProductTypeView

* ProductSubTypeView

* Base View Model

### CODE REVIEW

**Comment by MattKraatz** [comment]
You planning to address the rest of Issue #138 ?

**Comment by matthamil** [comment]
@MattKraatz Yep, currently resolving the rest of the issue. PR is WIP. Went ahead and opened it anyway ¯\_(ツ)_/¯

**Comment by matthamil** [comment]
@TeamCharles/team Ready for review

**Comment by garrett-vangilder** [comment]
Throws an error after you log on and select cart.

**Comment by matthamil** [comment]
~~Things got buggy after I merged the new Master into this branch. Currently resolving issues.~~

Issues resolved.

**Review by MattKraatz — APPROVED** [review]
LGTM

**Comment by MattKraatz** [comment]
image

**Comment by garrett-vangilder** [comment]
LGTM

**Review by daynewright — CHANGES_REQUESTED** [review]
The `Confirmation.cshtml` needs to be wrapped in the same `@if (isActive)` tag on the products.  If you checkout with inactive products in your cart it shows those on the final view.

**Review by daynewright — APPROVED** [review]

**Comment by Anulfo** [comment]
LGTM

**Pull request merged**
