### PR TITLE
hotfix-cartPriceColorFix - Removed red color from prices

### PR DESCRIPTION
**Pull request by matthamil**
## Status
**READY**

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.

## Description
Prices in cart view are no longer red.

## Deploy Notes

```sh
git pull --prune
git checkout hotfix-CartPriceColorFix
dotnet run
```

## Steps to Test or Reproduce

1. Log in

2. Have products in your cart

3. View Cart

## Impacted Files in Application

* Cart view

### CODE REVIEW

**Comment by garrett-vangilder** [comment]
LGTM

**Review by garrett-vangilder — APPROVED** [review]

**Review by MattKraatz — APPROVED** [review]
LGTM after merge conflicts

**Comment by daynewright** [comment]
LGTM

**Comment by matthamil** [comment]
This PR's changes are included in https://github.com/TeamCharles/initial-site/pull/145

**Pull request closed without merging**
