### PR TITLE
11 layout

### PR DESCRIPTION
**Pull request by garrett-vangilder**
## Status

READY
## Documentation

[X] I have fully documented features in this PR. Please put an `X` in the box to confirm.
## Migrations

NO
## Description

A few sentences describing the overall goals of the pull request's commits.

This PR was intended to change the layout and include a dropdown menu for users to select their name. Unfortunately the controller has not been built yet, so there is currently fake data within the `_layout.cshtml` file.
## Related PRs

List related PRs against other branches:

| branch | PR |
| --- | --- |
| other_pr_production | [link]() |
| other_pr_master | [link]() |
## Resolves Issue Number

number [link]()
#11
## Deploy Notes

Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.
## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.

``` sh
git pull --prune
git checkout 11-layout
dotnet run
```
1. 
## Impacted Areas in Application

List general components of the application that this PR will affect:
- No other areas are impacted upon through this PR.

### CODE REVIEW

**Comment by garrett-vangilder** [comment]
@daynewright sorry dude

**Comment by matthamil** [comment]
We could probably plan for the future and update this line of code for when we merge in #56 (resolves #43):

Line 55, `Views/Shared/_Layout.cshtml`:

`<li><a asp-area="" asp-controller="Customers" asp-action="Index">@customer</a></li>`

The `asp-action` could be set to something like `asp-action="SetActiveUser" asp-route-id="@user.UserId"` which could link to a function in the controller that doesn't exist yet (but will handle the active user logic).

Also, I think since we renamed our `Customer` model to `User`, we should stick with the current convention and replace occurrences of "Customer" with "User" in `_Layout.cshtml`.

**Comment by garrett-vangilder** [comment]
@matthamil I made a changes to the `asp-action` tag. I decided not to change the `asp-route` due to the fact that our routes have not been completely planned. This should be an easy fix in the near future. 

I also changed `asp-controller` to more closely follow our naming convention.

**Comment by matthamil** [comment]
LGTM

**Comment by MattKraatz** [comment]
LGTM, we'll need our manager to help us with this dropdown stuff.

**Comment by daynewright** [comment]
LGTM

**Review by daynewright — APPROVED** [review]
Works on my machine!

**Comment by Anulfo** [comment]
LGTM

**Pull request merged**
