### PR TITLE
changed the deleteLineItem to take the first instance of the line item

### PR DESCRIPTION
**Pull request by garrett-vangilder**
## Status
**READY**

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.

## Description
A few sentences describing the overall goals of the pull request's commits.

There was a bug that would happen when there were duplicate items in a cart, now the delete lineitem function takes the first instance that matches the lync query, this ensures that the error will not be thrown 

## Resolves Issue Number

#147 

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

```sh
git pull --prune
git checkout 147-delete-line-item
dotnet run
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1. Add two of anything to your cart.
2. View your cart
3. Delete one of the duplicates from your cart. 

## Impacted Files in Application
List general components of the application that this PR will affect:

* CartController.cs

### CODE REVIEW

**Review by MattKraatz — APPROVED** [review]
LGTM. Not necessarily the best solution, but will have no adverse effects on the functionality of our app.

**Comment by matthamil** [comment]
LGTM 👌

**Comment by daynewright** [comment]
LGTM

**Comment by Anulfo** [comment]
LGTM

**Pull request merged**
